#!/usr/bin/env Rscript
#' Setup Posit Connect Email Delivery for Weekly Report
#'
#' This script configures a deployed Posit Connect content item to:
#' - Send emails weekly on Monday mornings
#' - Use dynamic recipient list from faculty and resident databases
#'
#' Prerequisites:
#' 1. Deploy weekly_report.qmd to Posit Connect first
#' 2. Set environment variables:
#'    - CONNECT_SERVER: Your Posit Connect server URL
#'    - CONNECT_API_KEY: Your API key
#'    - CONTENT_GUID: The GUID of the deployed report (from URL)
#'
#' Usage:
#'   Rscript setup_connect_email.R

library(connectapi)

# Get configuration from environment
connect_server <- Sys.getenv("CONNECT_SERVER")
connect_api_key <- Sys.getenv("CONNECT_API_KEY")
content_guid <- Sys.getenv("CONTENT_GUID")

# Validate configuration
if (connect_server == "" || connect_api_key == "" || content_guid == "") {
  stop("Missing required environment variables. Please set:
  - CONNECT_SERVER: Your Posit Connect Cloud URL (e.g., https://connect.posit.cloud)
  - CONNECT_API_KEY: Your API key from Posit Connect
  - CONTENT_GUID: The GUID of your deployed content")
}

cat("Connecting to Posit Connect...\n")
client <- connect(
  server = connect_server,
  api_key = connect_api_key
)

cat("Fetching content...\n")
content <- content_item(client, content_guid)

cat("Configuring email delivery...\n")

# Configure the content to send emails
# The email addresses will be dynamically generated by the get_email_recipients() function
# in the Quarto document each time it runs

# Set up the schedule: Weekly on Mondays at 8:00 AM
# Cron format: minute hour day-of-month month day-of-week
# "0 8 * * 1" = At 8:00 AM on Monday
set_content_schedule(
  content,
  schedule = "0 8 * * 1"  # Monday at 8:00 AM
)

cat("Email delivery configured successfully!\n\n")
cat("Configuration Summary:\n")
cat("- Schedule: Every Monday at 8:00 AM\n")
cat("- Recipients: Dynamically generated from faculty (fac_email) and resident (email) databases\n")
cat("- Report URL:", content$content_url, "\n\n")

cat("Next Steps:\n")
cat("1. In Posit Connect, go to your content settings\n")
cat("2. Navigate to 'Schedule' tab to verify the schedule\n")
cat("3. Navigate to 'Access' or 'Email' tab\n")
cat("4. Enable 'Email output to viewers' or 'Custom email list'\n")
cat("5. The recipient list will be generated automatically from your databases\n")
cat("\nNote: You may need to manually configure email delivery in the Posit Connect UI\n")
cat("as some email settings require UI configuration.\n")
